config/routes.rb
FoundationApp::Application.routes.draw do

  namespace :api, defaults: {format: :json} do
    resources :companies, only: [:index, :create, :update, :destroy, :show]
  end

  resources :sessions, only: [:new, :create, :destroy]

  get '/dashboard' => 'templates#index'
  get '/templates/:path.html' => 'templates#template', :constraints => { :path => /.+/  }

  root  'sessions#new'
end

app/models/company.rb
class Company < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
  before_create :create_remember_token
  has_many :companies, foreign_key: :user_id

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/api/base_controller.rb
class Api::BaseController < ApplicationController
  # before_filter :authenticate_user!

  private
    def permission_denied
      render json: {error: 'unauthorized'}, status: :unauthorized
    end
end

app/controllers/api/companies_controller.rb
class Api::CompaniesController < Api::BaseController
  # before_action :check_owner, only: [:show, :update, :destroy]
  # before_action only: [:show, :update, :destroy]
  respond_to :html, :json

  def index
    # render json: current_user.companies
    # respond_with current_user.companies
    respond_with Company.all
  end

  def show
    # render json: company
    # respond_with company
    respond_with Company.all
  end

  def create
    company = current_user.companies.create!(safe_params)
    render json: company
  end

  def update
    company.update_attributes(safe_params)
    render nothing: true
  end

  def destroy
    # company = Company.find(params[:id])
    company.destroy
    render nothing: true, status: 204
  end

  private
    # def check_owner
    #   permission_denied if current_user != company.owner
    # end

    def company
      @company ||= Company.find(params[:id])
    end

    def safe_params
      params.require(:company).permit(:name, :url)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or dashboard_path
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController
  # before_filter signed_in_user
  layout "ng-app"

  def index
    # render layout: "app_layout"
  end

  def template
    render :template => 'templates/' + params[:path], :layout => nil
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  # def show
  #   @user = User.find(params[:id])
  # end
  def show
    # @user = User.find(params[:id])
    # @microposts = @user.microposts.paginate(page: params[:page])

    @user = User.find(params[:id])
    render json: @user
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end    
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    # Before filters

    # def signed_in_user
    #   redirect_to signin_url, notice: "Please sign in." unless signed_in?
    # end
    
    # Now this is moved to the session helper
    # def signed_in_user
    #   unless signed_in?
    #     store_location
    #     redirect_to signin_url, notice: "Please sign in."
    #   end
    # end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/ng-app.html.erb
<!DOCTYPE html>
<html ng-app="ngApp">
<head>
  <title>AngularApp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<!-- Fixed navbar -->
  <!-- <div class="navbar navbar-default navbar-fixed-top" role="navigation" ng-controller="NavCtrl">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="/dashboard" class="navbar-brand">Hacker News</a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a href="/new">New</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#" ng-click="open()">Submit</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Profile <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="/modify">Modify</a></li>
              <li><a href="/posts">Your Posts</a></li>
              <li><a href="/comments">Your Comments</a></li>
              <li class="divider"></li>
              <li><%= link_to 'Logout', sessions_path, :method=>'delete' %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div> -->

  <nav class="top-bar" data-topbar ng-controller="NavCtrl">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1>
        <a href="#">
          Hacker News
        </a>
      </h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="divider"></li>
      <li><a ><div a-leftpanel="#leftpanel_container">custom left panel holder</div></a></li>
      <li class="divider"></li>
      <li><a ><div slide-toggle="#derp">left panel holder</div></a></li>
      <li class="divider"></li>
      

      <li class="divider"></li>
      <li><a href="#" ng-click="open()">Submit Post</a></li>
      <li class="divider"></li>
      <li class="has-dropdown">
        <a href="#">Profile</a>
        <ul class="dropdown">
          <li><a href="#">Your Posts</a></li>
          <li><a href="#">Your Comments</a></li>
        </ul>
      </li>
      <li class="divider"></li>
      <li><a href="#">Log In</a></li>
    </ul>
  </section>
</nav>

<%= yield %>

<div id="derp" class="slideable" duration="500ms">
  <div>
    afasdfasdfasdfasdfasdf<br/>afasdfasdfasdfasdfasdf<br/>
  </div>
  <div>
    5455645645 56456 4564 56456 456 5645645<br/>545648489484  
  </div>
</div>

<div id="leftpanel_container">
  <div class="aside-backdrop am-fade a-fade"></div>
  <div class="aside ng-scope left am-slide-left" tabindex="-1" role="dialog">

    <div class="aside-dialog">
      <div class="aside-content">
        <div class="aside-header" ng-show="title">
          <button type="button" class="close" ng-click="$hide()">×</button>
          <h4 class="aside-title ng-binding" ng-bind-html="title">Title</h4>
        </div>

        <div class="aside-body" ng-show="content">
          <h4>Text in aside</h4>
          <p ng-bind-html="content" class="ng-binding">Hello Aside<br>
          This is a multiline message!</p>
          <pre class="ng-binding">2 + 3 = 5</pre>
          <h4>Popover in aside</h4>
          <p>This <button type="button" class="btn btn-default popover-test ng-scope" data-title="A Title" data-content="And here's some amazing content. It's very engaging. right?" bs-popover="">button</button> should trigger a popover on click.</p>
          <h4>Tooltips in aside</h4><p>
          <a href="#" class="tooltip-test ng-scope" data-title="Tooltip" bs-tooltip="">This link</a> and <a href="#" class="tooltip-test ng-scope" data-title="Tooltip" bs-tooltip="">that link</a> should have tooltips on hover.</p>
        </div>
        <div class="aside-footer">
          <button type="button" class="btn btn-default a-fade">Close</button> 
        </div>
      </div>
    </div>
    
    </div>
</div>

<!-- <div id="leftpanel_container">
  <div class="aside-backdrop am-fade a-fade"></div>
  <div class="aside ng-scope left am-slide-left" tabindex="-1" role="dialog">

    <div class="aside-dialog">
      <div class="aside-content">
        <div class="aside-header" ng-show="title">
          <button type="button" class="close" ng-click="$hide()">×</button>
          <h4 class="aside-title ng-binding" ng-bind-html="title">Title</h4>
        </div>

        <div class="aside-body" ng-show="content">
          <h4>Text in aside</h4>
          <p ng-bind-html="content" class="ng-binding">Hello Aside<br>
          This is a multiline message!</p>
          <pre class="ng-binding">2 + 3 = 5</pre>
          <h4>Popover in aside</h4>
          <p>This <button type="button" class="btn btn-default popover-test ng-scope" data-title="A Title" data-content="And here's some amazing content. It's very engaging. right?" bs-popover="">button</button> should trigger a popover on click.</p>
          <h4>Tooltips in aside</h4><p>
          <a href="#" class="tooltip-test ng-scope" data-title="Tooltip" bs-tooltip="">This link</a> and <a href="#" class="tooltip-test ng-scope" data-title="Tooltip" bs-tooltip="">that link</a> should have tooltips on hover.</p>
        </div>
        <div class="aside-footer">
          <button type="button" class="btn btn-default a-fade">Close</button> 
        </div>
      </div>
    </div>
    
    </div>
</div> -->

</body>
</html>

app/views/templates/animatedemo.html.erb
<div ng-app="ngApp" ng-controller="AnimateCtrl">
    <div class="boundingBox">
       <div class="circle"
           ng-repeat="shape in shapes"
           animate="shape"
           />
    </div>
</div>

app/views/templates/dashboard.html.erb
<!-- <div class="container">
  
  <div class="company row" ng-repeat="(id, company) in companies">
    <div class="col-xs-1">

    </div>
    <div class="col-md-9 col-xs-11">

      <div class="info">
        <a href="{{ company.url }}">
          {{ company.name }}
          <span class="url">({{ company.url | hostnameFromUrl }})</span>
        </a>
      </div>

      <div>
        <span>submitted by <a href="#/users/{{ company.user_id }}">{{ company.owner }}</a></span>
        —
        <a ng-click="editCompany(company)" href="#">edit</a>
        <a ng-click="deleteCompany(company)" href="#">delete</a>
      </div>
    </div>
    <div class="col-md-2">

    </div>

  </div>

</div> -->
<div style="width:600px; paddding:15px;">
  <!-- This is step 3
  <div ng-controller="ParentCtrl" class="scope">
    <input type="text" ng-model="model.title">
    <button ng-click="$child.childTesting()">Greet</button>

    <div ng-controller="ChildCtrl" class="scope">
      <input type="text" ng-model="model.title">
      <input type="text" ng-model="model.content">
      <button ng-click="$parent.testing()">Set Model</button>
      <button ng-click="greet()">Greet</button>
    </div>
  </div> -->

  <!-- 
  To check the ng repeat and fill data by ajax($http)
  <div ng-controller="FriendsCtrl" class="scope">
    <button ng-click="loadFriends()">Load Friends</button>
    <ul>
      <li ng-repeat="friend in friends">
        {{friend.name}},{{friend.url}}
      </li>
    </ul>
  </div> -->

  <!-- EXAMPLE TO TEST THE INLINE EDIT AND DELET AND CANCEL FUNCTIONALITY -->
  
    <h1>Title</h1>
    
    <p>Click on a title or edit link to edit. Cancel edit and changes should 
    revert to previous value. Press save to trigger some other handler.</p>
   
    <ul>
      <li ng-repeat="todo in todos" inline-edit="todo.title" on-save="updateTodo(todo.title)" on-cancel="cancelEdit(todo.title)">
        <div>
        <input type="text" on-enter="save()" on-esc="cancel()" ng-model="model" ng-show="editMode">
        <button ng-click="cancel()" ng-show="editMode">cancel</button>
        <button ng-click="save()" ng-show="editMode">save</button>
        <span ng-mouseenter="showEdit = true" ng-mouseleave="showEdit = false">
          <span ng-hide="editMode" ng-click="edit()">{{todo.title}}</span>
          <a ng-show="showEdit" ng-click="edit()">edit</a>
        </span>
        </div>
      </li>
    </ul>
    
    <div>{{todos}}</div>
  

</div>

app/views/templates/edit_company.html.erb
<form id="new_task" class="ng-pristine ng-valid" ng-submit="updateCompany()">
	<div class="modal-header">
	    <h3>Submit Company</h3>
	</div>
	<div class="modal-body">
	  <div class="form-group">
	    <input type="text" placeholder="Company Name" ng-model="company.name" maxlength="255" id="taskDescription" data-non-blank="" class="form-control input-lg ng-pristine ng-valid" autofocus="autofocus" required>
	  </div>
	  <div class="form-group">
	    <input type="text" placeholder="URL" ng-model="company.url" maxlength="255" id="taskDescription" data-non-blank="" class="form-control input-lg ng-pristine ng-valid" autofocus="autofocus" required>
	  </div>
	</div>
	<div class="modal-footer">
	  <button type="submit" class="btn btn-primary">Submit</button>
	  <button type="button" class="btn btn-warning" ng-click="cancel()">Cancel</button>
	</div>
</form>

app/views/templates/index.html.erb
<div class="ng-cloak">
  <div ng-view=""></div>
</div>

app/views/templates/submit_company.html.erb
<form id="new_task" class="ng-pristine ng-valid" ng-submit="submitCompany()">
	<div class="modal-header">
	    <h3>Submit Company</h3>
	</div>
	<div class="modal-body">
	  <div class="form-group">
	    <input type="text" placeholder="Company Name" ng-model="company.name" maxlength="255" id="taskDescription" data-non-blank="" class="form-control input-lg ng-pristine ng-valid" autofocus="autofocus" required>
	  </div>
	  <div class="form-group">
	    <input type="text" placeholder="URL" ng-model="company.url" maxlength="255" id="taskDescription" data-non-blank="" class="form-control input-lg ng-pristine ng-valid" autofocus="autofocus" required>
	  </div>
	</div>
	<div class="modal-footer">
	  <button type="submit" class="btn btn-primary">Submit</button>
	  <button type="button" class="btn btn-warning" ng-click="$close()">Cancel</button>
	</div>
</form>